### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by XinyeDu1204** [tae898/erc#20]
Hey, I saw that in 'multimodal-datasets', there is only the datasets about face-feature, but this project only use text part. 
Is there any sharing of the text part of IEMOCAP dataset? Thanks!

**Comment by tae898** [comment]
Hey there,

The text features are extracted by RoBERTa. Since it's relatively easy to extract them by running the huggingface model, I didn't upload them. Do you still think you need them?

**Comment by XinyeDu1204** [comment]
Thanks for your reply! Are the files in the “multimodal-datasets-main\IEMOCAP\raw-texts” file processed data? Can you share the code which process the data in IEMOCAP dataset? Thank you very much!

**Comment by tae898** [comment]
Welcome!

The files in that directory are very closes to the raw data. I just made them in an utterance level.

Below is an example from [`multimodal-datasets/IEMOCAP/raw-texts/train/Ses01F_impro01_F000.json`](https://github.com/tae898/multimodal-datasets/blob/main/IEMOCAP/raw-texts/train/Ses01F_impro01_F000.json)

```json
{
    "Utterance": "Excuse me.",
    "StartTime": 6.2901,
    "EndTime": 8.2357,
    "Speaker": "Female",
    "Emotion": "neutral",
    "SessionID": "Ses01"
}
```
Processing the IEMOCAP raw data happens here: [`multimodal-datasets/utils/extract_raw_data_iemocap.py `](https://github.com/tae898/multimodal-datasets/blob/main/utils/extract_raw_data_iemocap.py)
 
Let me know if you have more questions!

**Comment by XinyeDu1204** [comment]
Thank you very much!
