### ISSUE TITLE
About Result

### ISSUE THREAD

**Issue by XinyeDu1204** [tae898/erc#21]
The first time I run the code, the result on the test dataset is more than 60. But when I ran the model again, the f1 score of the model was only about 8%, but I didn't modify any code. Do you know what caused this?
Thank you!

**Comment by tae898** [comment]
Hi,

Can you provide me with more information?

* What's the data? MELD or IEMOCAP?
* What code did you actually run?
* Are there any codes, logs, messages that I can take a look at?

Thanks!

**Comment by XinyeDu1204** [comment]
Thank you! I have solved this problem. 
Because I ran this project again in the result of the last run, which led to this problem.
