### ISSUE TITLE
Fail to create hp.json

### ISSUE THREAD

**Issue by WayerLiu** [tae898/erc#25]
Hi there, 
Thank you for your work! I am trying to use your model, but there is a problem when running the code:

```console
***** Running training *****
  Num examples = 193
  Num Epochs = 15
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 195
  0%|                                                     | 0/1 [00:00<?, ?it/s]2022-04-05 02:07:51.274 INFO train-erc-text-full - <module>: arguments given to train-erc-text-full.py: {'OUTPUT_DIR': 'results/MELD/roberta-base/SEEDS/2022-04-05-02-07-09-speaker_mode-None-num_past_utterances-0-num_future_utterances-0-batch_size-16-seed-42', 'SEED': 42, 'DATASET': 'MELD', 'model_checkpoint': 'roberta-base', 'speaker_mode': None, 'num_past_utterances': 0, 'num_future_utterances': 0, 'BATCH_SIZE': 16, 'HP_ONLY_UPTO': 20, 'NUM_TRAIN_EPOCHS': 15, 'WEIGHT_DECAY': 0.01, 'WARMUP_RATIO': 0.2, 'HP_N_TRIALS': 10, 'SEEDS': [42]}
Traceback (most recent call last):
  File "train-erc-text-full.py", line 162, in <module>
    main(**args)
  File "train-erc-text-full.py", line 38, in main
    with open(os.path.join(OUTPUT_DIR, "hp.json"), "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'results/MELD/roberta-base/SEEDS/2022-04-05-02-07-09-speaker_mode-None-num_past_utterances-0-num_future_utterances-0-batch_size-16-seed-42/hp.json'
```

There is the folder 'results/MELD/roberta-base/SEEDS/2022-04-05-02-07-09-speaker_mode-None-num_past_utterances-0-num_future_utterances-0-batch_size-16-seed-42' but it seems _train-erc-text-hp.py_ fail to create json.hp file. The only change I did to the code is in _train-erc-text-hp.py_, changing FP16 from True to False (because I am using CPU for training.)

I wonder if you could offer any help here? Thanks in advance.

**Comment by tae898** [comment]
Hey there,

Yeah obviously `hp.json` is not generated by `train-erc-text-hp.py`.
Can you give me more console output when you run

```sh
python train-erc-text.py
```
?

I want to see what's happening when it runs [train-erc-text-hp.py](https://github.com/tae898/erc/blob/main/train-erc-text-hp.py)

**Comment by WayerLiu** [comment]
Yes, sure! It goes as follows:
[output.txt](https://github.com/tae898/erc/files/8417226/output.txt)

**Comment by tae898** [comment]
This is what it should be running for the hyperparameter tuning:

```console
Trial:
loading configuration file https://huggingface.co/roberta-base/resolve/main/config.json from cache at /home/tk/.cache/huggingface/transformers/733bade19e5f0ce98e6531021dd5180994bb2f7b8bd7e80c7968805834ba351e.35205c6cfc956461d8515139f0f8dd5d207a2f336c0c3a83b4bc8dca3518e37b
Model config RobertaConfig {
  "_name_or_path": "roberta-base",
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5",
    "6": "LABEL_6"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "LABEL_5": 5,
    "LABEL_6": 6
  },
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.16.2",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}

loading weights file https://huggingface.co/roberta-base/resolve/main/pytorch_model.bin from cache at /home/tk/.cache/huggingface/transformers/51ba668f7ff34e7cdfa9561e8361747738113878850a7d717dbc69de8683aaad.c7efaa30a0d80b2958b876969faa180e485944a849deee4ad482332de65365a7
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['lm_head.dense.weight', 'roberta.pooler.dense.weight', 'lm_head.dense.bias', 'lm_head.decoder.weight', 'lm_head.bias', 'lm_head.layer_norm.bias', 'roberta.pooler.dense.bias', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/tk/.virtualenvs/dev-python3.8/lib/python3.8/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use thePyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 278
  Num Epochs = 15
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 270
{'loss': 1.9485, 'learning_rate': 1.5878408305735611e-06, 'epoch': 1.0}                                                 
  7%|█████▍                                                                            | 18/270 [00:02<00:26,  9.58it/s]***** Running Evaluation *****
  Num examples = 328
  Batch size = 32
{'eval_loss': 1.9371755123138428, 'eval_runtime': 0.3253, 'eval_samples_per_second': 1008.43, 'eval_steps_per_second': 33.819, 'epoch': 1.0}                                                                                                    
{'loss': 1.9388, 'learning_rate': 3.1756816611471222e-06, 'epoch': 2.0}                                                 
 13%|██████████▉                                                                       | 36/270 [00:04<00:25,  9.13it/s]***** Running Evaluation *****
  Num examples = 328
  Batch size = 32
{'eval_loss': 1.9209282398223877, 'eval_runtime': 0.3516, 'eval_samples_per_second': 932.928, 'eval_steps_per_second': 31.287, 'epoch': 2.0}                                                                                                    
{'loss': 1.9056, 'learning_rate': 4.763522491720683e-06, 'epoch': 3.0}                                                  
 20%|████████████████▍                                                                 | 54/270 [00:06<00:24,  8.75it/s]***** Running Evaluation *****
  Num examples = 328
  Batch size = 32
{'eval_loss': 1.894093632698059, 'eval_runtime': 0.3823, 'eval_samples_per_second': 858.063, 'eval_steps_per_second': 28.777, 'epoch': 3.0}                                                                                                     
{'loss': 1.8359, 'learning_rate': 4.366562284077293e-06, 'epoch': 4.0}                                                  
 27%|█████████████████████▊                                                            | 72/270 [00:09<00:22,  8.77it/s]***** Running Evaluation *****
  Num examples = 328
  Batch size = 32
{'eval_loss': 1.8484244346618652, 'eval_runtime': 0.3263, 'eval_samples_per_second': 1005.292, 'eval_steps_per_second': 33.714, 'epoch': 4.0}                                                                                                   
{'loss': 1.7265, 'learning_rate': 3.969602076433903e-06, 'epoch': 5.0}                                                  
 33%|███████████████████████████▎                                                      | 90/270 [00:11<00:19,  9.43it/s]***** Running Evaluation *****
  Num examples = 328
  Batch size = 32
{'eval_loss': 1.7720708847045898, 'eval_runtime': 0.331, 'eval_samples_per_second': 991.02, 'eval_steps_per_second': 33.235, 'epoch': 5.0}                                                                                                      
{'loss': 1.6592, 'learning_rate': 3.59469521365959e-06, 'epoch': 6.0}                                                   
 40%|████████████████████████████████▍                                                | 108/270 [00:13<00:20,  8.00it/s]***** Running Evaluation *****
  Num examples = 328
  Batch size = 32
{'eval_loss': 1.7661951780319214, 'eval_runtime': 0.3778, 'eval_samples_per_second': 868.225, 'eval_steps_per_second': 29.117, 'epoch': 6.0}                                                                                                    
{'loss': 1.5861, 'learning_rate': 3.1977350060161995e-06, 'epoch': 7.0}                                                 
 47%|█████████████████████████████████████▊                                           | 126/270 [00:16<00:17,  8.27it/s]***** Running Evaluation *****
  Num examples = 328
  Batch size = 32
{'eval_loss': 1.7316522598266602, 'eval_runtime': 0.3293, 'eval_samples_per_second': 996.13, 'eval_steps_per_second': 33.407, 'epoch': 7.0}                                                                                                     
{'loss': 1.5266, 'learning_rate': 2.800774798372809e-06, 'epoch': 8.0}                                                  
 53%|███████████████████████████████████████████▏                                     | 144/270 [00:18<00:14,  8.92it/s]***** Running Evaluation *****
  Num examples = 328
  Batch size = 32
{'eval_loss': 1.6967371702194214, 'eval_runtime': 0.3306, 'eval_samples_per_second': 992.108, 'eval_steps_per_second': 33.272, 'epoch': 8.0}                                                                                                    
 60%|████████████████████████████████████████████████▎    
```

Did you have your data downloaded?

**Comment by tae898** [comment]
Did you do this?

https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by WayerLiu** [comment]
Hi, I downloaded the data from the submodules in the zip form and replace the empty folder with data before the mentioned output. I also tried the git clone method just now, but it gave me a similar output.
[output2.txt](https://github.com/tae898/erc/files/8417812/output2.txt)

**Comment by tae898** [comment]
Can you type

```sh
tree -L  4
```

and type what it outputs?

**Comment by tae898** [comment]
in the root repo directory.

**Comment by WayerLiu** [comment]
Ok, here it is:

wayer@ubuntu:~/v2/erc-main$ tree -L 4
.
├── app.py
├── client.py
├── docker
│   ├── Dockerfile-base
│   ├── Dockerfile-base-cuda
│   ├── Dockerfile-large
│   └── Dockerfile-large-cuda
├── images
│   ├── pred-excited_truth-excited.pdf
│   ├── pred-joy_truth-anger.pdf
│   ├── pred-joy_truth-joy.pdf
│   └── pred-neutral_truth-frustration.pdf
├── LICENSE
├── Makefile
├── multimodal-datasets
│   ├── annotate-emissor.py
│   ├── CarLani
│   │   ├── dataset-stats.md
│   │   ├── emotions.json
│   │   ├── raw-texts
│   │   │   └── train
│   │   ├── README.txt
│   │   └── utterance-ordered.json
│   ├── extract-dataset.py
│   ├── extract-features.py
│   ├── IEMOCAP
│   │   ├── dataset-stats.md
│   │   ├── emotions.json
│   │   ├── raw-texts
│   │   │   ├── test
│   │   │   ├── train
│   │   │   └── val
│   │   ├── README.txt
│   │   ├── undecided-emotions.json
│   │   └── utterance-ordered.json
│   ├── LICENSE
│   ├── Makefile
│   ├── MELD
│   │   ├── dataset-stats.md
│   │   ├── emotions.json
│   │   ├── raw-texts
│   │   │   ├── test
│   │   │   ├── train
│   │   │   └── val
│   │   ├── README.txt
│   │   └── utterance-ordered.json
│   ├── README.md
│   ├── requirements-annotate-emissor.txt
│   ├── requirements-extract-dataset.txt
│   ├── requirements-extract-features.txt
│   └── utils
│       ├── audio.py
│       ├── convert_cp1252_to_utf8.py
│       ├── extract_archive.py
│       ├── extract_raw_data_carlani.py
│       ├── extract_raw_data_iemocap.py
│       ├── extract_raw_data_meld.py
│       ├── IEMOCAP-DialogXL
│       │   ├── dev_data.json
│       │   ├── README.txt
│       │   ├── test_data.json
│       │   └── train_data.json
│       └── __init__.py
├── notebooks
│   ├── deploy-to-huggingface.ipynb
│   ├── model-test.ipynb
│   └── training-results-fp16-batched.ipynb
├── README.md
├── requirements-client.txt
├── requirements-deploy.txt
├── requirements.txt
├── results
│   ├── IEMOCAP
│   │   └── roberta-large
│   │       └── final
│   ├── MELD
│   │   ├── roberta-base
│   │   │   └── SEEDS
│   │   └── roberta-large
│   │       └── final
│   ├── qualitative-analysis.md
│   ├── results.csv
│   └── sota.json
├── train-erc-text-full.py
├── train-erc-text-hp.py
├── train-erc-text.py
├── train-erc-text.yaml
├── utils
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-38.pyc
│   │   └── utils.cpython-38.pyc
│   └── utils.py
└── utterance-ordered-MELD_IEMOCAP.json

30 directories, 64 files

**Comment by tae898** [comment]
It's always nice a nice practice to mark the beginning and the end of a code snippet / console output in markdown!

![image](https://user-images.githubusercontent.com/10544311/161754228-2c5f4f75-f4b3-4274-9890-572c2a9fa838.png)
![image](https://user-images.githubusercontent.com/10544311/161754251-e46122d8-1a37-471f-b4a5-6dbeb75032c1.png)

**Comment by tae898** [comment]
sorry can you also type

```sh
tree -L 5
```

**Comment by tae898** [comment]
More pro tips!

![image](https://user-images.githubusercontent.com/10544311/161754477-a72d7cc5-55eb-4ea0-b6ea-5899715bb20b.png)

**Comment by WayerLiu** [comment]
> More pro tips!
> 
> ![image](https://user-images.githubusercontent.com/10544311/161754477-a72d7cc5-55eb-4ea0-b6ea-5899715bb20b.png)
> 
> ![image](https://user-images.githubusercontent.com/10544311/161754634-54aa938e-9a79-4ff4-bdd0-4f69a88a7b92.png)

**Comment by WayerLiu** [comment]
Thanks for your advice! Will pay attention next time. Here `tree -L 5` gives me too many results for copying into a file, but I am pretty sure that there are required content in those folders:
![1649162732(1)](https://user-images.githubusercontent.com/57646770/161756496-9c363ac1-8861-4738-b33f-f2321b5160d3.png)

**Comment by WayerLiu** [comment]
Sorry, I accidentally closed this issue..

**Comment by tae898** [comment]
hmm alright ...
did of course do

```sh
pip install -r requirements.txt
```
?

**Comment by tae898** [comment]
Does this directoy actually exist?

`results/MELD/roberta-base/SEEDS/2022-04-05-06-42-47-speaker_mode-None-num_past_utterances-0-num_future_utterances-0-batch_size-16-seed-42`

**Comment by tae898** [comment]
Can you try changing

`DATASET: MELD_IEMOCAP` to `DATASET: MELD` in `train-erc-text.yaml` and run again?

**Comment by WayerLiu** [comment]
Wow yes I guess that's where the problem is. I reduce the batch size and it is now working. Thank you for you kind answer!

**Comment by tae898** [comment]
haha nice we solved it!
